### Homework 3 Numpy Arrays

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into an numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [3]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])


1. How can you get help on `np.array`?

Call dir() on np.array.

Call dir() on car.

Note the difference. `car` has methods and attributes we can use.

In [ ]:
#We can use help function which is a built-in function in numpy 
help(np.array)
#dir(np.array) showing the attributes and methods within the array
dir(np.array)
#dir(car) showing the methods we can use for car. Noticed that dir(np.array)and dir(car) doesn't have the same attributes or methods , they have their own methods and attributes.
dir(car)

 2.What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [7]:
print(car.dtype)
print(mpg.dtype)
print(horsepower.dtype)
print(origin.dtype)

object
float64
float64
object


3.`numpy` is often imported as `np`. What is this action called? Why might you do this? 

In [ ]:
#we are giving an alias as np to numpy , it is easy to call everytime we run the code 

4.Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [3]:
car.ndim

1

5.Show how to:

- multiply the `mpg` array by 12.
- divide the `mpg` array by 3.
- raise the `mpg` array to the power of 4.
- take the square root of the `mpg` array.

In [1]:
#print(mpg * 12)
#print(mpg / 3)
#print(mpg ** 4)
#print(np.sqrt(mpg))

6.What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help)

In [13]:
print(np.sum(horsepower))
print(np.min(horsepower))
print(np.max(horsepower))
print(np.median(horsepower))

42033.0
0.0
230.0
93.5


7.Select a subset of `acceleration`. 

- Select only the first 5 elements.
- Select every other element (new selection).

In [19]:
acceleration[:5]

array([12. , 11.5, 11. , 12. , 10.5])

In [17]:
acceleration[5:-1]

array([10. ,  9. ,  8.5, 10. ,  8.5, 17.5, 11.5, 11. , 10.5, 11. , 10. ,
        8. ,  8. ,  9.5, 10. , 15. , 15.5, 15.5, 16. , 14.5, 20.5, 17.5,
       14.5, 17.5, 12.5, 15. , 14. , 15. , 13.5, 18.5, 14.5, 15.5, 14. ,
       19. , 20. , 13. , 15.5, 15.5, 15.5, 15.5, 12. , 11.5, 13.5, 13. ,
       11.5, 12. , 12. , 13.5, 19. , 15. , 14.5, 14. , 14. , 19.5, 14.5,
       19. , 18. , 19. , 20.5, 15.5, 17. , 23.5, 19.5, 16.5, 12. , 12. ,
       13.5, 13. , 11.5, 11. , 13.5, 13.5, 12.5, 13.5, 12.5, 14. , 16. ,
       14. , 14.5, 18. , 19.5, 18. , 16. , 17. , 14.5, 15. , 16.5, 13. ,
       11.5, 13. , 14.5, 12.5, 11.5, 12. , 13. , 14.5, 11. , 11. , 11. ,
       16.5, 18. , 16. , 16.5, 16. , 21. , 14. , 12.5, 13. , 12.5, 15. ,
       19. , 19.5, 16.5, 13.5, 18.5, 14. , 15.5, 13. ,  9.5, 19.5, 15.5,
       14. , 15.5, 11. , 14. , 13.5, 11. , 16.5, 17. , 16. , 17. , 19. ,
       16.5, 21. , 17. , 17. , 18. , 16.5, 14. , 14.5, 13.5, 16. , 15.5,
       16.5, 15.5, 14.5, 16.5, 19. , 14.5, 15.5, 14

8.Show how to select the number `99` in the array below. 

In [24]:
select_99 = np.array([[1,2,3],
                      [4,5,99]])
select_99[1,2]

99

9.Select the last element in each subarray (do this with one operation.)

In [22]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])



In [31]:
select_more[:,2]

array([3, 6, 9])

10.Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [43]:
#here we are taking mean function and checking mean of mpg 
np.mean(mpg)


23.051231527093595

11.You your google skills to find the unique items in `origin`. (This may not have been covered in the readings.)

In [27]:
#type(origin)
origin_test = [0,6,5,0,6,5]
np.unique(origin_test)

array([0, 5, 6])

12.
- Create a 2D array and print its shape as well as ndim. (Any shape is fine)

- Create a 3D array and print its shape as well as ndim.

- Create a 4D array and print its shape as well as ndim. *It's hard to visualize 4-Dimensions but numpy can do it with ease!*

In [37]:
#2D array
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a.ndim)
#3D array
b = np.array([[[2,3,4],[5,6,7],[8,9,10]]])
print(b.ndim)
print(b.shape)
#4D array
c = np.array([[[[1,2],[3,4],[5,6],[7,8]]]])
print(c.ndim)
print(c.shape)

(2, 3)
2
3
(1, 3, 3)
4
(1, 1, 4, 2)


13.Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [32]:
origin == 'US'

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False, False, False,
       False, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False, False, False,  True, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False, False,  True,  True, False,  True,  True, False, False,
       False, False,

14.Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [50]:
car[origin == 'US']

array(['Chevrolet Chevelle Malibu', 'Buick Skylark 320',
       'Plymouth Satellite', 'AMC Rebel SST', 'Ford Torino',
       'Ford Galaxie 500', 'Chevrolet Impala', 'Plymouth Fury iii',
       'Pontiac Catalina', 'AMC Ambassador DPL',
       'Chevrolet Chevelle Concours (sw)', 'Ford Torino (sw)',
       'Plymouth Satellite (sw)', 'AMC Rebel SST (sw)',
       'Dodge Challenger SE', "Plymouth 'Cuda 340",
       'Ford Mustang Boss 302', 'Chevrolet Monte Carlo',
       'Buick Estate Wagon (sw)', 'Plymouth Duster', 'AMC Hornet',
       'Ford Maverick', 'AMC Gremlin', 'Ford F250', 'Chevy C20',
       'Dodge D200', 'Hi 1200D', 'Chevrolet Vega 2300', 'Ford Pinto',
       'AMC Gremlin', 'Plymouth Satellite Custom',
       'Chevrolet Chevelle Malibu', 'Ford Torino 500', 'AMC Matador',
       'Chevrolet Impala', 'Pontiac Catalina Brougham',
       'Ford Galaxie 500', 'Plymouth Fury iii', 'Dodge Monaco (sw)',
       'Ford Country Squire (sw)', 'Pontiac Safari (sw)',
       'AMC Hornet Sportabout (

15.Why might you prefer an `np.array()` over a Python `list`? And when is a Python `list` preferred? 

In [6]:
#np.array() is faster than list and NumPy have optimized functions such as linear algebra operations built in and it doesn't take much space.
#list take all types of data types like strings , integers etc. if programmer need all types data then list is preferred 

16.What is an identity matrix? 
Create an identiy matrix of size 5 using an np method. 

In [5]:
#identity matrix is a square array with ones on the main diagonal
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

17.Transpose the following array. 

In [12]:
transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
np.transpose(transpose_me)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**The remaining questions are OPTIONAL**: The readings did not address all of these so you may have to use some "Google-Fu". 

1.Why does this multiplication operation fail? 

In [ ]:
arr1 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
arr2 = np.array([[1,2,3],
                      [4,5,6]])

arr1 * arr2 


Use numpy to answer the following questions. 

2.What is the average horsepower for `Europe` cars? (Hint: create boolean index of 'US' apply it to horsepower and perform the calculation.)

3.On average are Japanse cars more fuel efficient than US cars? 

4.What is the correlation coefficient of `mpg` and `weight`? What is a correlaton coefficient?